name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 📥 Install dependencies
        run: npm ci

      - name: ▶️ Run lint script
        run: npm run lint

  test:
    name:
      🧪 Test (Node@${{ matrix.node }} - ESLint@${{ matrix.eslint }} - ${{
      matrix.os }})
    strategy:
      matrix:
        eslint: [8]
        node: [18.18.0, 20.9.0, 21.1.0, 22, 24]
        os: [ubuntu-latest]
        include:
          # ESLint v10
          - eslint: 10
            node: 24
            os: ubuntu-latest
          # ESLint v9
          - eslint: 9
            node: 22
            os: ubuntu-latest
          # On other platforms
          - os: windows-latest
            eslint: 8
            node: 22
          - os: macos-latest
            eslint: 8
            node: 22
          # On the minimum supported ESLint/Node.js version
          - eslint: 7.0.0
            node: 18.18.0
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: 📥 Install dependencies
        run: npm ci

      - name: 📥 Install ESLint v${{ matrix.eslint }}
        run: npm install eslint@${{ matrix.eslint }}

      - name: 📥 Install @typescript-eslint/parser v8
        run: npm install @typescript-eslint/parser@8 --force
        if: matrix.eslint == 10

      - name: ▶️ Run test script
        run: npm run test -- --runInBand

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
